<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login email or password is invalid Emai_07b851</name>
   <tag></tag>
   <elementGuidId>e9be599b-2c72-4453-866e-1c9447c141d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-main__wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06809d2f-ecdd-46a0-9ba6-d2a0a9bdd27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-main__wrap</value>
      <webElementGuid>88bc41d4-5265-49a8-b0a6-7b44ccf8d625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login email or password is invalid EmailPasswordLogin Belum memiliki akun? Register</value>
      <webElementGuid>6e2ec156-029f-4df1-a614-e1e792f76482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]</value>
      <webElementGuid>760147d2-f8c0-4c79-ab6d-e0f646b5cf14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div</value>
      <webElementGuid>976911d2-65c9-4c7c-91d7-30c8bffbd4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[2]</value>
      <webElementGuid>1526307a-a649-4ded-b0ce-61ab5f56374b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>548164f1-af9f-48da-b073-3d6af2bb3563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Login email or password is invalid EmailPasswordLogin Belum memiliki akun? Register' or . = 'Login email or password is invalid EmailPasswordLogin Belum memiliki akun? Register')]</value>
      <webElementGuid>4a35eabe-12f4-47d1-8fc9-983092959423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
