<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login password is required EmailPasswor_65985b</name>
   <tag></tag>
   <elementGuidId>7a7c804c-90d2-4903-88ac-d8b60b480c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-main__wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>188265c8-2b46-470e-a141-2dfdef23e505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-main__wrap</value>
      <webElementGuid>7e860c8a-edd1-4c13-acf3-1136821e0d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login password is required EmailPasswordLogin Belum memiliki akun? Register</value>
      <webElementGuid>45029a1d-cb79-4529-927e-c1919fed2140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]</value>
      <webElementGuid>c745feb3-b21c-43dc-9c9b-7cf38df3f5be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div</value>
      <webElementGuid>df83ad10-78d9-4746-b36b-db18c91e93a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[2]</value>
      <webElementGuid>438903c5-bb9d-40df-9134-5ecbbde813c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>8b52dd51-929e-4837-9c64-3e4e11f88bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Login password is required EmailPasswordLogin Belum memiliki akun? Register' or . = 'Login password is required EmailPasswordLogin Belum memiliki akun? Register')]</value>
      <webElementGuid>37a5ac07-7e48-4b1d-9b5f-24a525d6cf91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
