<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login record not found EmailPasswordLog_7d5b77</name>
   <tag></tag>
   <elementGuidId>ef7817cb-a67b-4a8c-824f-8485fd3e6350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-main__wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0d978cd-6253-402a-b32c-8fbb753018e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-main__wrap</value>
      <webElementGuid>2c6a6874-2817-4ef2-a9b1-9615f49deca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login record not found EmailPasswordLogin Belum memiliki akun? Register</value>
      <webElementGuid>d9eea89b-b721-4424-bc8e-786964e638b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]</value>
      <webElementGuid>31f3bb0b-53d0-4169-98cf-114fc2ee24e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div</value>
      <webElementGuid>410471db-0e0f-4ca6-8041-97fd434b25f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[2]</value>
      <webElementGuid>25138073-95ed-4f30-9c19-8f5fff223a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>f5189ad7-a63a-406f-a403-324977072c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Login record not found EmailPasswordLogin Belum memiliki akun? Register' or . = 'Login record not found EmailPasswordLogin Belum memiliki akun? Register')]</value>
      <webElementGuid>2e4b274f-694a-404c-8f83-046265636bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
