<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-21</name>
   <tag></tag>
   <elementGuidId>42bba2ac-7d68-4774-a7b2-bcdc0b6056d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-21']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/main/div/div/div/div[2]/form/div[2]/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/main/div/div/div/div[2]/form/div[2]/div/div[1]/div/input</value>
      <webElementGuid>3714b302-7e4d-4477-a54e-f0b0db13f125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-21']</value>
      <webElementGuid>d9fc39d6-a0ad-4025-81ce-aa49d1afd40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>d821da6f-7267-43cc-a605-21c8ddf2c612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>d223f31c-2b1a-4a8d-b0ca-7ab8ec01ded4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-21' and @type = 'text']</value>
      <webElementGuid>eb570a00-deaa-4303-97f2-79fd38ad42de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
