<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pofil</name>
   <tag></tag>
   <elementGuidId>a976465c-b30a-4ded-a131-c32d232c453a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/header/div/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/header/div/button[2]/span</value>
      <webElementGuid>aa0a4d83-f843-4680-b8d3-45fb441692fd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
