<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profil</name>
   <tag></tag>
   <elementGuidId>2ed6b374-6ece-47b7-b19c-e0965ee7d72d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/header/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/header/div/button[2]</value>
      <webElementGuid>e8cafdc4-66f1-47e8-add9-f3024a0b384c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
