<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sony PS5Rp 299-3Sony PS5Rp 299-1aRp 299_938c08</name>
   <tag></tag>
   <elementGuidId>c1ebcd50-f89a-4351-9380-ae19303eb07c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-card__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07c19031-b77e-449d-b513-903bfcfe1fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-card__text</value>
      <webElementGuid>01d8cc64-6ba6-4bed-b11c-709284b79f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sony PS5Rp 299-3+Sony PS5Rp 299-1+aRp 299-3+Total Qty7Total Bayar2093</value>
      <webElementGuid>97bd7764-7c0e-44de-85a6-0f6db43eda24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]</value>
      <webElementGuid>e6939861-583f-4625-b5a7-2307d7f628a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div</value>
      <webElementGuid>255458aa-260c-453d-afed-e2129bd40035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[6]</value>
      <webElementGuid>1cd5346c-9d55-46ec-aebd-b4775b6a1b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div</value>
      <webElementGuid>469ae208-2cff-4c26-b2ca-c1cec9e3f3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sony PS5Rp 299-3+Sony PS5Rp 299-1+aRp 299-3+Total Qty7Total Bayar2093' or . = 'Sony PS5Rp 299-3+Sony PS5Rp 299-1+aRp 299-3+Total Qty7Total Bayar2093')]</value>
      <webElementGuid>d0c74869-9282-42fd-a2c9-435d88654881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
