<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gaming Sony PS5  play has no limits  Rp_e48fdc</name>
   <tag></tag>
   <elementGuidId>8b379ffb-1907-4dc7-8f60-82a752adf66f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/main/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-main__wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/main/div/div/div[2]/div/div</value>
      <webElementGuid>6b9338a1-1ab7-481d-a0a6-44b012e9e042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div</value>
      <webElementGuid>a6dd51e7-2c06-4aa7-b6b7-3b78862b1ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AltaShop'])[1]/following::div[3]</value>
      <webElementGuid>d4379bdb-b6cb-4a94-b11a-7809773a9523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>beec5878-aeb6-431d-978c-fe10df21473b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'gaming Sony PS5  play has no limits   Rp 299DetailBeli' or . = 'gaming Sony PS5  play has no limits   Rp 299DetailBeli')]</value>
      <webElementGuid>4b9b774b-9fdc-4546-8b94-cf7f21c54e5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
