<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Transaksi_v-icon notranslate fas fa-sign-_24d4df</name>
   <tag></tag>
   <elementGuidId>cc0cfb16-3e68-46f0-b480-0b5c8cc736c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-670']/div/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[3]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.fas.fa-sign-in.theme--light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[3]/div/div[2]</value>
      <webElementGuid>9cbe01b9-0491-4ea7-93f9-dd60add2875c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-670']/div/i</value>
      <webElementGuid>b87f3607-1ed4-418b-b42c-35975f89df7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/i</value>
      <webElementGuid>eb7e31e3-9381-4e32-a679-4baf2854cc3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
