<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gaming2</name>
   <tag></tag>
   <elementGuidId>c47ee952-c364-4f5d-b4b1-ca0eec903a61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[2]/div/div[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[2]/div/div[13]</value>
      <webElementGuid>6cde49d3-cac8-4937-ae3b-dd60d9693b6d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
