<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sonyCategory</name>
   <tag></tag>
   <elementGuidId>180edf76-a019-4af5-b3ff-c3f53ee40eb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/main/div/div/div[2]/div/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/main/div/div/div[2]/div/div/div/div[1]</value>
      <webElementGuid>7ea396d9-971a-420a-81a4-cfb41072898f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
